# Generated by Django 4.2.1 on 2023-05-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_rename_tehnology_userblog_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('project_preview', models.ImageField(blank=True, null=True, upload_to='project/preview/', verbose_name='Картинка проекта')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('project_github', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка github проекта')),
                ('project_date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project_published', models.BooleanField(default=True)),
                ('project_view_count', models.IntegerField(default=0, verbose_name='Просмотры проекта')),
                ('project_technology', models.ManyToManyField(related_name='project', to='profiles.technology')),
                ('project_user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
