version: '3.7'

services:
  backend_blog:
    build: ./
    command: >
      bash -c "./manage.py makemigrations && ./manage.py migrate  && ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db-dev
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  db-dev:
    image: postgres:14
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "54321:5432"

volumes:
  dev_postgres_data: