# Generated by Django 4.2.1 on 2023-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userblog_bio_userblog_birthday_userblog_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6, verbose_name='Пол'),
        ),
    ]
