# Generated by Django 4.2.1 on 2023-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userblog_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя технологии.')),
            ],
        ),
        migrations.AddField(
            model_name='userblog',
            name='tehnology',
            field=models.ManyToManyField(related_name='users', to='profiles.technology'),
        ),
    ]
