# Generated by Django 4.2.1 on 2023-05-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_technology_userblog_tehnology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblog',
            old_name='tehnology',
            new_name='technology',
        ),
    ]
